version: "3.1"

services:
  
  nginx:
    image: nginx:alpine
    environment:
      VIRTUAL_HOST: yz-app.online
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: yz-app.online
      LETSENCRYPT_EMAIL: karl10011001@gmail.com
    expose: 
      - 8000
    volumes:
      - ./php/content:/srv/www/content
      - ./static:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - nodejs

  nodejs:
    image: node:alpine
    environment: 
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    volumes:
      - ./nodejs:/home/app
    depends_on:
      - php
    command: ["node", "index"]

  php:
    image: php:apache
    volumes:
      - ./php:/var/www/html

networks:
  default:
    external:
      name: nginx-proxy
